/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pfc;

import dados.Bean.Usuario;
import javax.swing.JOptionPane;
import pfcDAO.funcionarioDAO;
import pfcDAO.usuarioDAO;

/**
 *
 * @author Balbicosta
 */
public class IFrameUsuario extends javax.swing.JInternalFrame {

    Usuario usur = new Usuario();
    usuarioDAO uDAO = new usuarioDAO();
    funcionarioDAO fDAO = new funcionarioDAO();

    /**
     * Creates new form IFrameUsuario
     */
    public IFrameUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        salvar = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        novaSenha = new javax.swing.JPasswordField();
        senhaAtual = new javax.swing.JPasswordField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Dados Usuário");
        setPreferredSize(new java.awt.Dimension(400, 400));

        jLabel1.setText("ID");

        jLabel2.setText("Senha ");

        jLabel3.setText("Confirmar Senha");

        salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/accept.png"))); // NOI18N
        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Id)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .addComponent(novaSenha)
                            .addComponent(senhaAtual, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(salvar)
                        .addGap(64, 64, 64)
                        .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(novaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvar)
                    .addComponent(sair))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        // Ação do botão SALVAR na tela de cadastro de USUÁRIO.
        String mat = Id.getText();
        // Verifica se o formulário está em branco
        if (mat.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Favor preencher o formulário.");
        }else{
            int ID = Integer.valueOf(mat);
            usur.setId(fDAO.listData(mat).getId());
            usur.setLogin(fDAO.listData(mat).getEmail());

            // Verifica se o USUÁRIO já está é um FUNCIONÁRIO cadastrado
            if (ID == fDAO.listData(mat).getId()) {
                String SenhaAtual = String.valueOf(senhaAtual.getPassword());
                String NovaSenha = String.valueOf(novaSenha.getPassword());
                usur.setSenha(NovaSenha);

                // Valida o cadastro da SENHA comparando se ambas são iguais.
                if (SenhaAtual.equals(NovaSenha)) {
                    JOptionPane.showMessageDialog(null, "Login e senha cadastrados com sucesso.");

                    // Chamada do método para alterar os dados na classe de Data Access Object usuarioDAO.
                    uDAO.saveData(usur);

                    // Limpa os campos da tela de cadastro de USUÁRIO após dados serem salvos no banco de dados.
                    Id.setText("");
                    senhaAtual.setText("");
                    novaSenha.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "Login incorreto ou senhas diferentes");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Funcionário não está cadastrado");
            }
        }
    }//GEN-LAST:event_salvarActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // Ação do botão SAIR na tela de cadastro de USUÁRIO.

        //Comando para FECHAR a tela de cadastro de USUÁRIO.
        this.dispose();
    }//GEN-LAST:event_sairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField novaSenha;
    private javax.swing.JButton sair;
    private javax.swing.JButton salvar;
    private javax.swing.JPasswordField senhaAtual;
    // End of variables declaration//GEN-END:variables
}
